
name: Test pull request

on:
  pull_request:

permissions:
  contents: read

jobs:

  test:

    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd pulumi && npm install

      - name: Run tests
        run: cd pulumi && npm run test

